import { useState, useMemo } from 'react'
import { Link } from 'react-router-dom'
import { motion } from 'framer-motion'
import { pageTransition } from '../../utils/animations'

const sections = [
  {
    id: 'sec-1',
    num: '1',
    title: 'ABOUT OMEDO',
    content: (
      <div className="space-y-3 text-sm leading-relaxed text-slate-800">
        <p>
          OMEDO is a healthcare management software platform designed to help hospitals, clinics, nursing homes, healthcare facilities, doctors, and other healthcare organizations manage and digitize their operational workflows.
        </p>
        <p>Depending on the subscription and configuration selected by the Customer, OMEDO may provide features including, but not limited to:</p>
        <ul className="list-disc pl-5 space-y-1 text-slate-700">
          <li>Patient Registration</li>
          <li>UHID Management</li>
          <li>Appointment Management</li>
          <li>OPD Management</li>
          <li>IPD Management</li>
          <li>Doctor Consultation</li>
          <li>Electronic Medical Records (EMR)</li>
          <li>Digital Prescription</li>
          <li>Nursing Management</li>
          <li>Laboratory Management</li>
          <li>Pharmacy Management</li>
          <li>Billing and Accounts</li>
          <li>Insurance / TPA Management</li>
          <li>Operation Theatre Management</li>
          <li>Oncology Management</li>
          <li>Radiotherapy Management</li>
          <li>Reports and Analytics</li>
          <li>Inventory Management</li>
          <li>User and Role Management</li>
          <li>Notifications and Communication</li>
          <li>Integration with third-party services</li>
          <li>Other healthcare management and administrative functions</li>
        </ul>
        <p>
          The availability of specific modules and features depends on the plan, subscription, implementation scope, and agreement between OMEDO and the Customer.
        </p>
      </div>
    ),
  },
  {
    id: 'sec-2',
    num: '2',
    title: 'DEFINITIONS',
    content: (
      <div className="space-y-3 text-sm leading-relaxed text-slate-800">
        <p>For the purpose of these Terms:</p>
        <div className="space-y-3">
          <div>
            <p className="font-bold text-slate-900">2.1 &quot;Company&quot;, &quot;OMEDO&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot;</p>
            <p className="text-slate-700">means OMEDO Software Solutions Private Limited, having its registered/official address at: H-11, Sector-23, Sanjay Nagar, Ghaziabad – 201002, Uttar Pradesh, India.</p>
          </div>
          <div>
            <p className="font-bold text-slate-900">2.2 &quot;Customer&quot;</p>
            <p className="text-slate-700">means any hospital, clinic, nursing home, doctor, diagnostic centre, healthcare organization, company, partnership, proprietorship, institution, or other legal entity that subscribes to or uses OMEDO.</p>
          </div>
          <div>
            <p className="font-bold text-slate-900">2.3 &quot;User&quot;</p>
            <p className="text-slate-700">means an individual authorized by the Customer to access or use OMEDO, including doctors, nurses, administrators, receptionists, pharmacists, accountants, technicians, or other employees or authorized personnel.</p>
          </div>
          <div>
            <p className="font-bold text-slate-900">2.4 &quot;Patient Data&quot;</p>
            <p className="text-slate-700">means information relating to patients entered, uploaded, generated, stored, or processed through OMEDO by or on behalf of the Customer.</p>
          </div>
          <div>
            <p className="font-bold text-slate-900">2.5 &quot;Customer Data&quot;</p>
            <p className="text-slate-700">means all data, records, documents, information, content, and other materials submitted, uploaded, entered, or generated by the Customer or its authorized Users while using OMEDO.</p>
          </div>
          <div>
            <p className="font-bold text-slate-900">2.6 &quot;Services&quot;</p>
            <p className="text-slate-700">means the software, platform, applications, hosting, support, implementation, integrations, updates, and other services provided by OMEDO.</p>
          </div>
        </div>
      </div>
    ),
  },
  {
    id: 'sec-3',
    num: '3',
    title: 'ACCEPTANCE OF TERMS',
    content: (
      <div className="space-y-3 text-sm leading-relaxed text-slate-800">
        <p>By using OMEDO, the Customer and its authorized Users confirm that:</p>
        <ol className="list-decimal pl-5 space-y-1.5 text-slate-700">
          <li>They have the legal authority to enter into this Agreement.</li>
          <li>The information provided during registration or onboarding is accurate and complete.</li>
          <li>They will use OMEDO only for lawful purposes.</li>
          <li>They will comply with all applicable laws and regulations.</li>
          <li>They will ensure that their employees and authorized Users comply with these Terms.</li>
        </ol>
        <p>Where the Customer is a legal entity, the individual accepting these Terms represents that they have the authority to bind that entity.</p>
      </div>
    ),
  },
  {
    id: 'sec-4',
    num: '4',
    title: 'ELIGIBILITY',
    content: (
      <div className="space-y-3 text-sm leading-relaxed text-slate-800">
        <p>OMEDO is intended primarily for use by healthcare organizations, healthcare professionals, administrative personnel, and authorized personnel.</p>
        <p>The Services must not be used by individuals who are legally incapable of entering into a binding agreement under applicable law.</p>
        <p>The Customer is responsible for ensuring that every person provided access to OMEDO is properly authorized.</p>
      </div>
    ),
  },
  {
    id: 'sec-5',
    num: '5',
    title: 'LICENSE TO USE OMEDO',
    content: (
      <div className="space-y-3 text-sm leading-relaxed text-slate-800">
        <p>
          Subject to payment of applicable fees and compliance with these Terms, OMEDO grants the Customer a limited, non-exclusive, non-transferable, non-sublicensable right to access and use the Services during the applicable subscription period.
        </p>
        <p>The Customer shall not:</p>
        <ul className="list-disc pl-5 space-y-1 text-slate-700">
          <li>Copy, reproduce, distribute, sell, lease, or sublicense OMEDO.</li>
          <li>Reverse engineer or attempt to derive the source code of OMEDO.</li>
          <li>Modify, adapt, or create derivative works from the software.</li>
          <li>Circumvent security mechanisms.</li>
          <li>Use OMEDO to develop a competing software product.</li>
          <li>Access or attempt to access another Customer&apos;s account or data.</li>
          <li>Use automated methods to interfere with the Services.</li>
          <li>Remove copyright, trademark, or proprietary notices.</li>
          <li>Allow unauthorized persons to access the Services.</li>
        </ul>
      </div>
    ),
  },
  {
    id: 'sec-6',
    num: '6',
    title: 'HEALTHCARE AND MEDICAL DISCLAIMER',
    content: (
      <div className="space-y-3 text-sm leading-relaxed text-slate-800">
        <p>OMEDO is a software and healthcare management platform. OMEDO is not a hospital, clinic, doctor, medical practitioner, diagnostic centre, pharmacy, or healthcare provider.</p>
        <p>OMEDO does not provide medical diagnosis, treatment, medical advice, clinical decision-making, or emergency medical services.</p>
        <p>The healthcare professional and/or Customer remains solely responsible for:</p>
        <ul className="list-disc pl-5 space-y-1 text-slate-700">
          <li>Patient diagnosis</li>
          <li>Medical treatment</li>
          <li>Prescription decisions</li>
          <li>Medication selection and dosage</li>
          <li>Clinical decisions</li>
          <li>Patient monitoring</li>
          <li>Medical records</li>
          <li>Patient consent</li>
          <li>Investigation interpretation</li>
          <li>Medical documentation</li>
          <li>Patient safety</li>
          <li>Compliance with applicable healthcare laws and professional standards</li>
        </ul>
        <p>Any clinical decision made using information displayed, stored, calculated, or processed through OMEDO remains the responsibility of the relevant healthcare professional.</p>
        <p>OMEDO should not be considered a substitute for professional medical judgment.</p>
      </div>
    ),
  },
  {
    id: 'sec-7',
    num: '7',
    title: 'CUSTOMER DATA AND PATIENT INFORMATION',
    content: (
      <div className="space-y-3 text-sm leading-relaxed text-slate-800">
        <p>The Customer retains ownership of its Customer Data and Patient Data.</p>
        <p>The Customer is responsible for ensuring that it has the necessary legal rights, permissions, notices, and consents required to collect, process, store, and use Patient Data through OMEDO.</p>
        <p>The Customer shall ensure that Patient Data is entered and maintained accurately.</p>
        <p>OMEDO may process Customer Data solely to the extent reasonably necessary to:</p>
        <ul className="list-disc pl-5 space-y-1 text-slate-700">
          <li>Provide the Services;</li>
          <li>Host and maintain the platform;</li>
          <li>Provide technical support;</li>
          <li>Perform backups;</li>
          <li>Maintain security;</li>
          <li>Troubleshoot technical issues;</li>
          <li>Improve reliability and performance;</li>
          <li>Provide integrations requested by the Customer;</li>
          <li>Comply with applicable legal obligations.</li>
        </ul>
        <p>OMEDO will handle personal and healthcare-related information in accordance with its applicable Privacy Policy and data protection obligations.</p>
      </div>
    ),
  },
  {
    id: 'sec-8',
    num: '8',
    title: 'CUSTOMER RESPONSIBILITY FOR DATA',
    content: (
      <div className="space-y-3 text-sm leading-relaxed text-slate-800">
        <p>The Customer is responsible for:</p>
        <ol className="list-decimal pl-5 space-y-1.5 text-slate-700">
          <li>The accuracy and completeness of information entered into OMEDO.</li>
          <li>Obtaining appropriate patient consent wherever required.</li>
          <li>Maintaining appropriate access controls.</li>
          <li>Creating appropriate User roles and permissions.</li>
          <li>Protecting login credentials.</li>
          <li>Ensuring that Users do not share their credentials.</li>
          <li>Maintaining the confidentiality of Patient Data.</li>
          <li>Using the system in accordance with applicable laws.</li>
        </ol>
        <p>OMEDO shall not be responsible for incorrect, incomplete, misleading, or unlawfully entered information supplied by the Customer or its Users.</p>
      </div>
    ),
  },
  {
    id: 'sec-9',
    num: '9',
    title: 'USER ACCOUNTS AND SECURITY',
    content: (
      <div className="space-y-3 text-sm leading-relaxed text-slate-800">
        <p>Each User must maintain the confidentiality of their username, password, OTP, authentication credentials, and other account information.</p>
        <p>The Customer is responsible for all activities performed through its account unless the Customer has promptly notified OMEDO of unauthorized access.</p>
        <p>The Customer should immediately notify OMEDO if it becomes aware of:</p>
        <ul className="list-disc pl-5 space-y-1 text-slate-700">
          <li>Unauthorized access;</li>
          <li>Lost credentials;</li>
          <li>Suspected security breach;</li>
          <li>Unauthorized disclosure of Patient Data;</li>
          <li>Suspicious activity.</li>
        </ul>
        <p>OMEDO may temporarily suspend an account where reasonably necessary to protect the platform, Customer Data, or other users.</p>
      </div>
    ),
  },
  {
    id: 'sec-10',
    num: '10',
    title: 'SUBSCRIPTION AND FEES',
    content: (
      <div className="space-y-3 text-sm leading-relaxed text-slate-800">
        <p>Access to certain OMEDO Services may require payment of subscription, implementation, integration, customization, support, maintenance, hosting, or other applicable fees.</p>
        <p>The applicable fees shall be communicated to the Customer through:</p>
        <ul className="list-disc pl-5 space-y-1 text-slate-700">
          <li>Quotation;</li>
          <li>Proposal;</li>
          <li>Order form;</li>
          <li>Subscription plan;</li>
          <li>Invoice;</li>
          <li>Agreement; or</li>
          <li>Other written communication accepted by the Customer.</li>
        </ul>
        <p>Unless otherwise agreed in writing, applicable taxes including GST shall be charged separately.</p>
        <p>The Customer is responsible for paying all applicable fees within the agreed payment period.</p>
      </div>
    ),
  },
  {
    id: 'sec-11',
    num: '11',
    title: 'PAYMENT DEFAULT',
    content: (
      <div className="space-y-3 text-sm leading-relaxed text-slate-800">
        <p>If the Customer fails to make payment within the agreed period, OMEDO may:</p>
        <ol className="list-decimal pl-5 space-y-1.5 text-slate-700">
          <li>Send payment reminders;</li>
          <li>Restrict certain Services;</li>
          <li>Suspend access;</li>
          <li>Charge applicable late payment fees where agreed;</li>
          <li>Terminate the subscription after providing reasonable notice.</li>
        </ol>
        <p>OMEDO will make reasonable efforts to notify the Customer before suspension where circumstances permit.</p>
      </div>
    ),
  },
  {
    id: 'sec-12',
    num: '12',
    title: 'IMPLEMENTATION AND CUSTOMIZATION',
    content: (
      <div className="space-y-3 text-sm leading-relaxed text-slate-800">
        <p>Depending on the Customer&apos;s requirements, OMEDO may provide implementation, configuration, migration, training, customization, integration, or deployment services.</p>
        <p>The scope, fees, timeline, and deliverables for such services may be separately agreed in writing.</p>
        <p>Any customization outside the agreed scope may be subject to additional charges and timelines.</p>
        <p>Implementation timelines may depend on the Customer providing required information, approvals, infrastructure, personnel, third-party credentials, and other dependencies.</p>
      </div>
    ),
  },
  {
    id: 'sec-13',
    num: '13',
    title: 'THIRD-PARTY INTEGRATIONS',
    content: (
      <div className="space-y-3 text-sm leading-relaxed text-slate-800">
        <p>OMEDO may integrate with third-party services such as:</p>
        <ul className="list-disc pl-5 space-y-1 text-slate-700">
          <li>Payment gateways</li>
          <li>SMS providers</li>
          <li>WhatsApp or communication platforms</li>
          <li>Banking services</li>
          <li>Government or healthcare platforms</li>
          <li>ABDM/ABHA-related services</li>
          <li>Laboratory equipment</li>
          <li>Insurance/TPA systems</li>
          <li>Other APIs and external services</li>
        </ul>
        <p>Third-party services may have their own terms, privacy policies, technical limitations, downtime, fees, or changes.</p>
        <p>OMEDO does not control third-party services and cannot guarantee their continuous availability.</p>
        <p>Where a third-party service becomes unavailable, changes its API, introduces restrictions, or discontinues its service, OMEDO shall not be responsible for such third-party failure.</p>
      </div>
    ),
  },
  {
    id: 'sec-14',
    num: '14',
    title: 'DATA BACKUP',
    content: (
      <div className="space-y-3 text-sm leading-relaxed text-slate-800">
        <p>OMEDO may maintain backups of Customer Data as part of its operational and disaster-recovery processes.</p>
        <p>However, backup systems cannot guarantee recovery from every possible event.</p>
        <p>Customers should maintain appropriate internal records and backups where required by their operational, legal, regulatory, or contractual obligations.</p>
        <p>OMEDO shall use commercially reasonable measures to protect and recover Customer Data in accordance with its applicable backup and recovery practices.</p>
      </div>
    ),
  },
  {
    id: 'sec-15',
    num: '15',
    title: 'SERVICE AVAILABILITY',
    content: (
      <div className="space-y-3 text-sm leading-relaxed text-slate-800">
        <p>OMEDO will make commercially reasonable efforts to maintain the availability and reliability of the Services.</p>
        <p>However, uninterrupted availability cannot be guaranteed.</p>
        <p>The Services may temporarily become unavailable due to:</p>
        <ul className="list-disc pl-5 space-y-1 text-slate-700">
          <li>Scheduled maintenance;</li>
          <li>Emergency maintenance;</li>
          <li>Software updates;</li>
          <li>Server or infrastructure failure;</li>
          <li>Internet failure;</li>
          <li>Cybersecurity incidents;</li>
          <li>Third-party service failures;</li>
          <li>Government or regulatory actions;</li>
          <li>Natural disasters;</li>
          <li>Force majeure events; or</li>
          <li>Other circumstances beyond OMEDO&apos;s reasonable control.</li>
        </ul>
      </div>
    ),
  },
  {
    id: 'sec-16',
    num: '16',
    title: 'SOFTWARE UPDATES',
    content: (
      <div className="space-y-3 text-sm leading-relaxed text-slate-800">
        <p>OMEDO may periodically release:</p>
        <ul className="list-disc pl-5 space-y-1 text-slate-700">
          <li>Bug fixes;</li>
          <li>Security updates;</li>
          <li>Performance improvements;</li>
          <li>New features;</li>
          <li>UI/UX improvements;</li>
          <li>Regulatory updates;</li>
          <li>Technical changes;</li>
          <li>Module enhancements.</li>
        </ul>
        <p>Some updates may be automatically applied while others may require Customer action.</p>
        <p>OMEDO may modify, replace, add, or discontinue features from time to time.</p>
      </div>
    ),
  },
  {
    id: 'sec-17',
    num: '17',
    title: 'INTELLECTUAL PROPERTY RIGHTS',
    content: (
      <div className="space-y-3 text-sm leading-relaxed text-slate-800">
        <p>All intellectual property rights relating to OMEDO, including but not limited to:</p>
        <ul className="list-disc pl-5 space-y-1 text-slate-700">
          <li>Software;</li>
          <li>Source code;</li>
          <li>Object code;</li>
          <li>Database structure;</li>
          <li>UI/UX designs;</li>
          <li>Logos;</li>
          <li>Trademarks;</li>
          <li>Graphics;</li>
          <li>Documentation;</li>
          <li>Website content;</li>
          <li>Algorithms;</li>
          <li>Workflows;</li>
          <li>Reports;</li>
          <li>System architecture;</li>
          <li>APIs;</li>
          <li>Product designs;</li>
        </ul>
        <p>belong to or are lawfully licensed to OMEDO Software Solutions Private Limited, unless otherwise expressly agreed in writing.</p>
        <p>Nothing in these Terms transfers ownership of OMEDO&apos;s intellectual property to the Customer.</p>
        <p>The Customer receives only the limited right to use the Services as permitted under these Terms.</p>
      </div>
    ),
  },
  {
    id: 'sec-18',
    num: '18',
    title: 'CUSTOMER INTELLECTUAL PROPERTY',
    content: (
      <div className="space-y-3 text-sm leading-relaxed text-slate-800">
        <p>The Customer retains ownership of its own trademarks, logos, documents, content, and Customer Data.</p>
        <p>The Customer grants OMEDO the limited rights necessary to host, process, transmit, display, back up, and otherwise process such content solely for providing the Services.</p>
      </div>
    ),
  },
  {
    id: 'sec-19',
    num: '19',
    title: 'PROHIBITED USE',
    content: (
      <div className="space-y-3 text-sm leading-relaxed text-slate-800">
        <p>The Customer and Users shall not use OMEDO to:</p>
        <ul className="list-disc pl-5 space-y-1 text-slate-700">
          <li>Conduct unlawful activities;</li>
          <li>Violate applicable laws;</li>
          <li>Upload malicious software;</li>
          <li>Introduce viruses or harmful code;</li>
          <li>Attempt unauthorized access;</li>
          <li>Attack or disrupt the platform;</li>
          <li>Circumvent security controls;</li>
          <li>Abuse APIs;</li>
          <li>Conduct fraudulent activities;</li>
          <li>Upload content that infringes third-party rights;</li>
          <li>Store unlawful content;</li>
          <li>Misuse Patient Data;</li>
          <li>Attempt to compromise other users&apos; accounts;</li>
          <li>Use the platform for activities unrelated to the intended healthcare-management purpose where such use creates security, legal, or operational risk.</li>
        </ul>
      </div>
    ),
  },
  {
    id: 'sec-20',
    num: '20',
    title: 'CONFIDENTIALITY',
    content: (
      <div className="space-y-3 text-sm leading-relaxed text-slate-800">
        <p>Each party may receive confidential information belonging to the other party.</p>
        <p>Confidential information may include:</p>
        <ul className="list-disc pl-5 space-y-1 text-slate-700">
          <li>Business information;</li>
          <li>Pricing;</li>
          <li>Technical information;</li>
          <li>Software architecture;</li>
          <li>Customer information;</li>
          <li>Patient information;</li>
          <li>Security information;</li>
          <li>Commercial information;</li>
          <li>Product roadmaps;</li>
          <li>Documentation.</li>
        </ul>
        <p>Each party shall take reasonable measures to protect confidential information and shall not disclose such information to unauthorized third parties except where required by law or necessary to provide the Services.</p>
      </div>
    ),
  },
  {
    id: 'sec-21',
    num: '21',
    title: 'PRIVACY AND DATA PROTECTION',
    content: (
      <div className="space-y-3 text-sm leading-relaxed text-slate-800">
        <p>Your use of OMEDO is also governed by our Privacy Policy, which forms part of these Terms.</p>
        <p>The Customer acknowledges that healthcare information and personal information may be subject to applicable privacy and data-protection laws.</p>
        <p>The Customer remains responsible for ensuring that its collection and processing of Patient Data through OMEDO is lawful and appropriately authorized.</p>
        <p>OMEDO will implement reasonable technical and organizational safeguards appropriate to the Services and applicable requirements.</p>
      </div>
    ),
  },
  {
    id: 'sec-22',
    num: '22',
    title: 'SUPPORT AND MAINTENANCE',
    content: (
      <div className="space-y-3 text-sm leading-relaxed text-slate-800">
        <p>OMEDO may provide technical support and maintenance according to the Customer&apos;s selected plan or separate agreement.</p>
        <p>Support may include:</p>
        <ul className="list-disc pl-5 space-y-1 text-slate-700">
          <li>Technical assistance;</li>
          <li>Issue resolution;</li>
          <li>Software guidance;</li>
          <li>User support;</li>
          <li>Bug fixes;</li>
          <li>Updates;</li>
          <li>Remote assistance;</li>
          <li>Training, where included.</li>
        </ul>
        <p>Support levels, response times, working hours, and service scope may vary depending on the Customer&apos;s subscription or service agreement.</p>
      </div>
    ),
  },
  {
    id: 'sec-23',
    num: '23',
    title: 'LIMITATION OF LIABILITY',
    content: (
      <div className="space-y-3 text-sm leading-relaxed text-slate-800">
        <p>To the maximum extent permitted by applicable law, OMEDO Software Solutions Private Limited shall not be liable for indirect, incidental, special, consequential, exemplary, or punitive damages, including loss of profits, business interruption, loss of goodwill, or loss of anticipated savings arising from the use of or inability to use the Services.</p>
        <p>OMEDO shall not be responsible for losses resulting from:</p>
        <ul className="list-disc pl-5 space-y-1 text-slate-700">
          <li>Incorrect data entered by Users;</li>
          <li>Incorrect medical or clinical decisions;</li>
          <li>Unauthorized access caused by Customer credential misuse;</li>
          <li>Third-party service failures;</li>
          <li>Internet or telecommunications failures;</li>
          <li>Customer infrastructure failures;</li>
          <li>Customer&apos;s failure to maintain appropriate security;</li>
          <li>Misuse of the platform;</li>
          <li>Events beyond OMEDO&apos;s reasonable control.</li>
        </ul>
        <p>Nothing in these Terms shall exclude or limit liability that cannot lawfully be excluded or limited under applicable law.</p>
      </div>
    ),
  },
  {
    id: 'sec-24',
    num: '24',
    title: 'MEDICAL AND OPERATIONAL RESPONSIBILITY',
    content: (
      <div className="space-y-3 text-sm leading-relaxed text-slate-800">
        <p>The Customer acknowledges that OMEDO is a technology platform and does not control the Customer&apos;s healthcare operations.</p>
        <p>The Customer remains responsible for:</p>
        <ul className="list-disc pl-5 space-y-1 text-slate-700">
          <li>Its doctors and medical professionals;</li>
          <li>Employees and staff;</li>
          <li>Patient treatment;</li>
          <li>Medical records;</li>
          <li>Billing decisions;</li>
          <li>Insurance claims;</li>
          <li>Regulatory compliance;</li>
          <li>Hospital policies;</li>
          <li>Patient communication;</li>
          <li>Clinical workflows;</li>
          <li>Data accuracy.</li>
        </ul>
        <p>OMEDO does not guarantee that use of the platform will eliminate operational, clinical, financial, or regulatory risks.</p>
      </div>
    ),
  },
  {
    id: 'sec-25',
    num: '25',
    title: 'SUSPENSION OF SERVICES',
    content: (
      <div className="space-y-3 text-sm leading-relaxed text-slate-800">
        <p>OMEDO may suspend or restrict access to the Services where reasonably necessary if:</p>
        <ul className="list-disc pl-5 space-y-1 text-slate-700">
          <li>The Customer violates these Terms;</li>
          <li>Fees remain unpaid;</li>
          <li>The account presents a security risk;</li>
          <li>The platform is being misused;</li>
          <li>There is suspected fraudulent or unlawful activity;</li>
          <li>Suspension is required by law;</li>
          <li>The Customer attempts unauthorized access;</li>
          <li>The Customer&apos;s use threatens the security or availability of the platform.</li>
        </ul>
        <p>Where reasonably practicable, OMEDO may provide prior notice before suspension.</p>
      </div>
    ),
  },
  {
    id: 'sec-26',
    num: '26',
    title: 'TERMINATION',
    content: (
      <div className="space-y-3 text-sm leading-relaxed text-slate-800">
        <p>Either party may terminate the applicable subscription or agreement in accordance with the agreed commercial terms.</p>
        <p>OMEDO may terminate the Services if the Customer:</p>
        <ul className="list-disc pl-5 space-y-1 text-slate-700">
          <li>Materially breaches these Terms;</li>
          <li>Fails to pay applicable fees;</li>
          <li>Engages in unlawful activity;</li>
          <li>Misuses the Services;</li>
          <li>Repeatedly violates security requirements;</li>
          <li>Uses OMEDO in a manner that creates material risk to OMEDO or other customers.</li>
        </ul>
        <p>Upon termination, the Customer&apos;s right to access the Services will cease, subject to any applicable data-retention or transition arrangements agreed between the parties.</p>
      </div>
    ),
  },
  {
    id: 'sec-27',
    num: '27',
    title: 'DATA AFTER TERMINATION',
    content: (
      <div className="space-y-3 text-sm leading-relaxed text-slate-800">
        <p>Following termination, OMEDO may retain or delete Customer Data in accordance with:</p>
        <ul className="list-disc pl-5 space-y-1 text-slate-700">
          <li>The applicable agreement;</li>
          <li>OMEDO&apos;s data-retention policies;</li>
          <li>Applicable legal requirements;</li>
          <li>Backup and disaster-recovery processes.</li>
        </ul>
        <p>Where data export is available, the Customer may request export of its data subject to the applicable technical limitations and commercial terms.</p>
        <p>Any special data migration or extraction service may be subject to additional charges where agreed.</p>
      </div>
    ),
  },
  {
    id: 'sec-28',
    num: '28',
    title: 'REFUND POLICY',
    content: (
      <div className="space-y-3 text-sm leading-relaxed text-slate-800">
        <p>Fees paid for subscriptions, implementation, customization, integration, training, support, or other Services shall be governed by the applicable quotation, order form, subscription plan, or agreement.</p>
        <p>Unless otherwise expressly agreed in writing, payments for completed implementation, customization, integration, professional services, or subscription periods already commenced may be non-refundable.</p>
        <p>Any refund, credit, or adjustment shall be subject to the applicable commercial agreement and applicable law.</p>
      </div>
    ),
  },
  {
    id: 'sec-29',
    num: '29',
    title: 'FORCE MAJEURE',
    content: (
      <div className="space-y-3 text-sm leading-relaxed text-slate-800">
        <p>OMEDO shall not be liable for delay or failure to perform its obligations where such delay or failure results from events beyond its reasonable control, including:</p>
        <ul className="list-disc pl-5 space-y-1 text-slate-700">
          <li>Natural disasters;</li>
          <li>Fire;</li>
          <li>Flood;</li>
          <li>Earthquake;</li>
          <li>War;</li>
          <li>Terrorism;</li>
          <li>Government action;</li>
          <li>Internet outages;</li>
          <li>Telecommunications failures;</li>
          <li>Cyberattacks;</li>
          <li>Epidemics or pandemics;</li>
          <li>Power failures;</li>
          <li>Cloud infrastructure failures;</li>
          <li>Strikes or labour disruptions;</li>
          <li>Other events beyond reasonable control.</li>
        </ul>
      </div>
    ),
  },
  {
    id: 'sec-30',
    num: '30',
    title: 'CHANGES TO THESE TERMS',
    content: (
      <div className="space-y-3 text-sm leading-relaxed text-slate-800">
        <p>OMEDO may modify these Terms from time to time to reflect changes in:</p>
        <ul className="list-disc pl-5 space-y-1 text-slate-700">
          <li>Services;</li>
          <li>Technology;</li>
          <li>Business practices;</li>
          <li>Applicable laws;</li>
          <li>Regulatory requirements;</li>
          <li>Security requirements.</li>
        </ul>
        <p>Updated Terms may be published on the OMEDO website.</p>
        <p>The updated version will become effective from the date stated in the revised Terms unless otherwise required by applicable law or agreement.</p>
        <p>Continued use of OMEDO after the effective date of revised Terms may constitute acceptance of the revised Terms.</p>
      </div>
    ),
  },
  {
    id: 'sec-31',
    num: '31',
    title: 'THIRD-PARTY LINKS AND SERVICES',
    content: (
      <div className="space-y-3 text-sm leading-relaxed text-slate-800">
        <p>The OMEDO website or platform may contain links to third-party websites, applications, products, or services.</p>
        <p>Such links are provided for convenience only.</p>
        <p>OMEDO does not control third-party websites or services and is not responsible for their:</p>
        <ul className="list-disc pl-5 space-y-1 text-slate-700">
          <li>Content;</li>
          <li>Availability;</li>
          <li>Security;</li>
          <li>Privacy practices;</li>
          <li>Accuracy;</li>
          <li>Terms;</li>
          <li>Performance.</li>
        </ul>
        <p>Users should review the applicable third-party terms and privacy policies before using those services.</p>
      </div>
    ),
  },
  {
    id: 'sec-32',
    num: '32',
    title: 'GOVERNING LAW',
    content: (
      <div className="space-y-3 text-sm leading-relaxed text-slate-800">
        <p>These Terms shall be governed by and interpreted in accordance with the laws of India.</p>
        <p>Subject to the dispute-resolution provisions contained in any separate agreement between OMEDO and the Customer, the courts having appropriate jurisdiction in Ghaziabad, Uttar Pradesh, India, shall have jurisdiction over disputes arising from these Terms.</p>
      </div>
    ),
  },
  {
    id: 'sec-33',
    num: '33',
    title: 'DISPUTE RESOLUTION',
    content: (
      <div className="space-y-3 text-sm leading-relaxed text-slate-800">
        <p>The parties shall first attempt to resolve any dispute arising from these Terms through good-faith discussions.</p>
        <p>If the dispute cannot be resolved amicably, the parties may pursue appropriate legal remedies in accordance with applicable Indian law.</p>
        <p>Where a separate written agreement between OMEDO and the Customer contains an arbitration clause, that arbitration clause shall govern the dispute.</p>
      </div>
    ),
  },
  {
    id: 'sec-34',
    num: '34',
    title: 'SEVERABILITY',
    content: (
      <div className="space-y-3 text-sm leading-relaxed text-slate-800">
        <p>If any provision of these Terms is determined to be invalid, illegal, or unenforceable, the remaining provisions shall continue to remain valid and enforceable.</p>
      </div>
    ),
  },
  {
    id: 'sec-35',
    num: '35',
    title: 'WAIVER',
    content: (
      <div className="space-y-3 text-sm leading-relaxed text-slate-800">
        <p>Failure by OMEDO to enforce any provision of these Terms shall not constitute a waiver of its right to enforce that provision or any other provision in the future.</p>
      </div>
    ),
  },
  {
    id: 'sec-36',
    num: '36',
    title: 'ENTIRE AGREEMENT',
    content: (
      <div className="space-y-3 text-sm leading-relaxed text-slate-800">
        <p>These Terms, together with the applicable:</p>
        <ul className="list-disc pl-5 space-y-1 text-slate-700">
          <li>Privacy Policy;</li>
          <li>Subscription Agreement;</li>
          <li>Order Form;</li>
          <li>Quotation;</li>
          <li>Service Agreement;</li>
          <li>Data Processing Agreement, where applicable;</li>
        </ul>
        <p>constitute the agreement governing the Customer&apos;s use of OMEDO, unless otherwise expressly agreed in writing.</p>
        <p>Where there is a conflict between these Terms and a separately signed written agreement, the separately signed agreement shall prevail to the extent of that conflict.</p>
      </div>
    ),
  },
  {
    id: 'sec-37',
    num: '37',
    title: 'CONTACT INFORMATION',
    content: (
      <div className="space-y-3 text-sm leading-relaxed text-slate-800">
        <p>If you have any questions, concerns, complaints, or requests regarding these Terms, please contact us:</p>
        <div className="p-4 bg-slate-50 border border-slate-200 rounded-2xl space-y-2">
          <p className="font-bold text-slate-900">OMEDO Software Solutions Private Limited</p>
          <div>
            <p className="font-semibold text-slate-800">Address:</p>
            <p className="text-slate-700">H-11, Sector-23, Sanjay Nagar,<br />Ghaziabad – 201002,<br />Uttar Pradesh, India</p>
          </div>
          <p className="text-slate-700"><strong>Email:</strong> <a href="mailto:support@omedosoft.com" className="text-[#00685e] hover:underline">support@omedosoft.com</a></p>
          <p className="text-slate-700"><strong>Website:</strong> <a href="https://www.omedosoft.com" target="_blank" rel="noopener noreferrer" className="text-[#00685e] hover:underline">www.omedosoft.com</a></p>
          <p className="text-slate-700"><strong>Phone:</strong> +91 96500 00000</p>
        </div>
      </div>
    ),
  },
]

export default function Terms() {
  const [searchQuery, setSearchQuery] = useState('')
  const [isTocCollapsed, setIsTocCollapsed] = useState(false)

  const filteredSections = useMemo(() => {
    if (!searchQuery.trim()) return sections
    const q = searchQuery.toLowerCase()
    return sections.filter((s) => s.title.toLowerCase().includes(q) || s.num.includes(q))
  }, [searchQuery])

  const scrollToSection = (id) => {
    const el = document.getElementById(id)
    if (el) {
      el.scrollIntoView({ behavior: 'smooth', block: 'start' })
    }
  }

  return (
    <motion.div {...pageTransition} className="min-h-screen bg-[#f8fdfe] pt-24 sm:pt-28 pb-16">
      
      {/* ── HEADER HERO ── */}
      <section className="bg-gradient-to-b from-[#effcfe] via-[#f5fdfe] to-[#f8fdfe] py-10 sm:py-16 border-b border-[#bcc9c6]/30">
        <div className="site-wrapper text-center max-w-6xl mx-auto px-4 space-y-5">
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-[#afecde]/80 text-[#00685e] text-xs sm:text-sm font-bold shadow-xs">
            <span className="material-symbols-outlined text-base">gavel</span>
            <span>Legal Documentation</span>
          </div>

          <h1
            className="text-3xl sm:text-4xl lg:text-5xl font-extrabold text-[#121d1f] tracking-tight leading-tight"
            style={{ fontFamily: "'Plus Jakarta Sans', sans-serif" }}
          >
            Terms &amp; <span className="text-[#00685e]">Conditions</span>
          </h1>

          <p className="text-sm sm:text-base text-slate-600 max-w-3xl mx-auto font-medium">
            Last Updated: <strong className="text-slate-900 font-bold">25-08-2026</strong>
          </p>

          {/* Intro Notice Banner (Word-for-Word from Document) */}
          <div className="w-full text-left p-6 sm:p-8 lg:p-10 bg-white rounded-3xl border border-[#00685e]/30 shadow-lg text-sm sm:text-base text-slate-800 leading-relaxed space-y-4">
            <p>
              Welcome to <strong>OMEDO</strong>, a healthcare management software platform owned and operated by <strong>OMEDO Software Solutions Private Limited</strong>.
            </p>
            <p>
              These Terms &amp; Conditions (&quot;Terms&quot;, &quot;Terms and Conditions&quot;, or &quot;Agreement&quot;) govern your access to and use of the OMEDO website, software, web application, mobile applications, services, features, and related products (collectively, the &quot;Services&quot;).
            </p>
            <p>
              By accessing, registering for, subscribing to, or using OMEDO, you acknowledge that you have read, understood, and agreed to be bound by these Terms.
            </p>
            <p className="font-semibold text-rose-700 bg-rose-50 p-3 rounded-xl border border-rose-200">
              If you do not agree with these Terms, you must not access or use the Services.
            </p>
          </div>
        </div>
      </section>

      {/* ── MAIN CONTENT CONTAINER (WIDER) ── */}
      <section className="site-wrapper py-8 sm:py-12 px-4 max-w-6xl mx-auto space-y-8">
        
        {/* ── TABLE OF CONTENTS CARD (COMPACT & STREAMLINED) ── */}
        <div id="table-of-contents" className="bg-white rounded-2xl p-3.5 sm:p-4 border border-[#bcc9c6]/50 shadow-xs space-y-3 scroll-mt-28">
          
          {/* Header Bar */}
          <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-2.5 pb-2.5 border-b border-slate-100">
            <div className="flex items-center gap-2">
              <div className="w-7 h-7 rounded-lg bg-[#effcfe] text-[#00685e] border border-[#afecde] flex items-center justify-center">
                <span className="material-symbols-outlined text-base">format_list_bulleted</span>
              </div>
              <h2 className="text-sm font-bold text-[#121d1f]" style={{ fontFamily: "'Plus Jakarta Sans', sans-serif" }}>
                Table of Contents
              </h2>
              <span className="text-[10px] font-bold px-2 py-0.2 rounded-full bg-[#afecde] text-[#00685e]">
                37 Clauses
              </span>
            </div>

            <div className="flex items-center gap-2 w-full sm:w-auto">
              {/* Search Bar */}
              <div className="relative flex-1 sm:w-56">
                <span className="material-symbols-outlined absolute left-2.5 top-1/2 -translate-y-1/2 text-slate-400 text-xs">
                  search
                </span>
                <input
                  type="text"
                  placeholder="Filter clauses..."
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  className="w-full pl-8 pr-2.5 py-1 rounded-lg text-xs border border-slate-200 focus:outline-none focus:border-[#00685e] focus:ring-1 focus:ring-[#00685e]/20"
                />
              </div>

              {/* Collapse/Expand toggle */}
              <button
                type="button"
                onClick={() => setIsTocCollapsed(!isTocCollapsed)}
                className="px-2 py-1 rounded-lg border border-slate-200 hover:bg-slate-50 text-slate-700 text-xs font-semibold flex items-center gap-1 transition-colors cursor-pointer shrink-0"
              >
                <span className="material-symbols-outlined text-sm">
                  {isTocCollapsed ? 'expand_more' : 'expand_less'}
                </span>
                <span>{isTocCollapsed ? 'Show' : 'Hide'}</span>
              </button>

              {/* Print Button */}
              <button
                type="button"
                onClick={() => window.print()}
                className="px-2 py-1 rounded-lg bg-slate-100 hover:bg-slate-200 text-slate-700 text-xs font-semibold flex items-center gap-1 transition-colors cursor-pointer shrink-0"
              >
                <span className="material-symbols-outlined text-xs">print</span>
                <span className="hidden sm:inline">Print</span>
              </button>
            </div>
          </div>

          {/* Compact 4-Column Grid of Clauses with Smooth Scroll */}
          {!isTocCollapsed && (
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-1.5 max-h-52 overflow-y-auto pr-1">
              {filteredSections.map((s) => (
                <button
                  key={s.id}
                  type="button"
                  onClick={() => scrollToSection(s.id)}
                  className="w-full text-left py-1.5 px-2 rounded-lg bg-[#effcfe]/30 hover:bg-[#effcfe] border border-transparent hover:border-[#afecde] text-slate-700 hover:text-[#00685e] transition-all flex items-center gap-2 group cursor-pointer"
                >
                  <span className="w-5 h-5 rounded-md bg-white border border-[#afecde] font-mono font-bold text-[9px] text-[#00685e] flex items-center justify-center shrink-0 group-hover:bg-[#00685e] group-hover:text-white transition-colors">
                    {s.num}
                  </span>
                  <span className="truncate font-medium text-[11px]">
                    {s.title}
                  </span>
                </button>
              ))}
            </div>
          )}

        </div>

        {/* ── ALL 37 CLAUSES (STARTING FROM 1. ABOUT OMEDO) ── */}
        <div className="space-y-6">
          {sections.map((sec) => (
            <div
              key={sec.id}
              id={sec.id}
              className="bg-white rounded-3xl p-6 sm:p-8 border border-[#bcc9c6]/40 shadow-xs hover:border-[#00685e]/40 transition-all scroll-mt-28 space-y-4"
            >
              <div className="flex items-center justify-between gap-3 border-b border-slate-100 pb-3">
                <div className="flex items-center gap-3">
                  <span className="w-8 h-8 rounded-xl bg-[#effcfe] text-[#00685e] border border-[#afecde] font-mono font-bold text-xs flex items-center justify-center shrink-0">
                    {sec.num}
                  </span>
                  <h3
                    className="text-base sm:text-lg font-bold text-[#121d1f] tracking-tight"
                    style={{ fontFamily: "'Plus Jakarta Sans', sans-serif" }}
                  >
                    {sec.num}. {sec.title}
                  </h3>
                </div>

                <button
                  type="button"
                  onClick={() => scrollToSection('table-of-contents')}
                  className="text-[11px] font-semibold text-[#00685e] hover:underline flex items-center gap-0.5 opacity-70 hover:opacity-100 transition-opacity cursor-pointer shrink-0"
                >
                  <span>Top</span>
                  <span className="material-symbols-outlined text-xs">arrow_upward</span>
                </button>
              </div>

              <div className="pt-1">
                {sec.content}
              </div>
            </div>
          ))}

          {/* Bottom Legal Support Card */}
          <div className="p-6 sm:p-8 bg-gradient-to-r from-[#00685e] to-[#004d46] text-white rounded-3xl shadow-md flex flex-col sm:flex-row items-center justify-between gap-4">
            <div>
              <div className="text-base sm:text-lg font-bold">Have questions about our Terms &amp; Conditions?</div>
              <div className="text-xs text-white/80">Our legal and customer support team is available to assist you.</div>
            </div>
            <Link
              to="/contact"
              className="px-6 py-2.5 rounded-full bg-white text-[#00685e] font-bold text-xs hover:bg-[#effcfe] transition-all shadow-sm shrink-0"
            >
              Contact Legal Support
            </Link>
          </div>
        </div>

      </section>

      {/* ── FLOATING QUICK TOP / TOC BUTTON ── */}
      <button
        type="button"
        onClick={() => scrollToSection('table-of-contents')}
        className="fixed bottom-6 right-6 z-40 p-3 rounded-full bg-[#00685e] text-white shadow-xl hover:bg-[#005049] transition-all flex items-center gap-1.5 text-xs font-bold cursor-pointer"
        title="Jump to Table of Contents"
      >
        <span className="material-symbols-outlined text-base">format_list_bulleted</span>
        <span className="hidden sm:inline">Table of Contents</span>
      </button>

    </motion.div>
  )
}
